
sudo: required
dist: trusty

language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

before_install:
  - travis/before-install-"$TRAVIS_OS_NAME"
  - git config --global user.email "someone@localhost"
  - git config --global user.name "Travis CI Build"

script:
  - make -j check
  - if [ "$TRAVIS_OS_NAME" = linux ]; then fakeroot make -j check; fi
  - sudo -i make -C "$(pwd -P)" -j check
  - sudo -i make -C "$(pwd -P)" install
